name: Create Release

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write
  pull-requests: read
  issues: read
  statuses: read
  actions: read

jobs:
  create-release:
    uses: liquibase/build-logic/.github/workflows/create-release.yml@main
    secrets: inherit
