name: Build and Test

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: write
  pull-requests: write
  packages: read
  id-token: write
  
jobs:

  authorize:
    environment: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name != github.repository && 'external' || 'internal' }}
    runs-on: ubuntu-latest
    steps:
      - run: "true"

  build-test:
    needs: authorize
    uses: liquibase/build-logic/.github/workflows/os-extension-test.yml@main
    secrets: inherit
    with:
      java: "[ 17, 21 ]"

  integration-tests:
    name: Integration Test - Java ${{ matrix.java }}
    runs-on: ubuntu-latest
    needs: build-test
    strategy:
      matrix:
        java: [17, 21]
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'adopt'
    - name: Test With Maven
      run: ./mvnw integration-test

  dependabot:
    needs: integration-tests
    uses: liquibase/build-logic/.github/workflows/dependabot-automerge.yml@main
    secrets: inherit
